name: Build & Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ~/.pnpm-store
          restore-keys: |
            ${{ runner.os }}-

      - name: Install PNPM package manager
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2

      - name: Build & Release Electron application
        uses: jcoon97/action-electron-builder@v1.7.0
        env:
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_ID_PASSWORD: ${{ secrets.apple_id_password }}
        with:
          build_script_name: cleanbuild

          github_token: ${{ secrets.github_token }}

          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          release: ${{ startsWith(github.ref, 'refs/tags/v') }}